# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'drugie.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import hashlib
from mess import messagebox
from db_conn import dbConnection
from list import Ui_FormList

class Ui_FormMainWindow(object):
    def setupUi(self, FormMainWindow):
        FormMainWindow.setObjectName("FormMainWindow")
        FormMainWindow.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormMainWindow)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelImie = QtWidgets.QLabel(FormMainWindow)
        self.labelImie.setObjectName("labelImie")
        self.verticalLayout.addWidget(self.labelImie)
        self.lineEditImie = QtWidgets.QLineEdit(FormMainWindow)
        self.lineEditImie.setObjectName("lineEditImie")
        self.verticalLayout.addWidget(self.lineEditImie)
        self.labelEmail = QtWidgets.QLabel(FormMainWindow)
        self.labelEmail.setObjectName("labelEmail")
        self.verticalLayout.addWidget(self.labelEmail)
        self.lineEditEmail = QtWidgets.QLineEdit(FormMainWindow)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.verticalLayout.addWidget(self.lineEditEmail)
        self.labelPassword = QtWidgets.QLabel(FormMainWindow)
        self.labelPassword.setObjectName("labelPassword")
        self.verticalLayout.addWidget(self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(FormMainWindow)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.verticalLayout.addWidget(self.lineEditPassword)
        self.pushButtonInsert = QtWidgets.QPushButton(FormMainWindow)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.verticalLayout.addWidget(self.pushButtonInsert)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(FormMainWindow)
        QtCore.QMetaObject.connectSlotsByName(FormMainWindow)
        self.pushButtonInsert.clicked.connect(self.insertRecord)

    def insertRecord(self):
        imie = self.lineEditImie.text()
        email = self.lineEditEmail.text()
        password = self.lineEditPassword.text()

        if imie != '' and email != '' and password != '':
            password = hashlib.md5(password.encode('utf-8')).hexdigest()
            params = (imie, email, password)
            query = """
                INSERT INTO users (imie, email, pass) VALUES (%s, %s, %s);
            """
            db = dbConnection()
            db.connect()
            curs = db.execute(query, params)
            db.close() 
            if curs.statusmessage == "INSERT 0 1":
                messagebox("Inserted","A new record has been inserted.","Information","Ok")
                
                FormMainWindow.hide()
            else:
                messagebox("Error","Record has not been inserted","Warning","Cancel")
        else:
            messagebox("Error","Niewprowadzono danych...","Warning","Cancel")
        

    def retranslateUi(self, FormMainWindow):
        _translate = QtCore.QCoreApplication.translate
        FormMainWindow.setWindowTitle(_translate("FormMainWindow", "Form"))
        self.labelImie.setText(_translate("FormMainWindow", "Imie:"))
        self.labelEmail.setText(_translate("FormMainWindow", "Email:"))
        self.labelPassword.setText(_translate("FormMainWindow", "Password:"))
        self.pushButtonInsert.setText(_translate("FormMainWindow", "Insert"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormMainWindow = QtWidgets.QWidget()
    ui = Ui_FormMainWindow()
    ui.setupUi(FormMainWindow)
    FormMainWindow.show()
    sys.exit(app.exec_())
