# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from db_conn import dbConnection
from mess import messagebox
from drugie import Ui_FormMainWindow
from PyQt5.QtWidgets import QTableWidgetItem
from login import Ui_FormLogin

class Ui_FormList(object):
    def setupUi(self, FormList):
        FormList.setObjectName("FormList")
        FormList.resize(416, 304)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormList)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(FormList)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.pushButtonClose = QtWidgets.QPushButton(FormList)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.verticalLayout.addWidget(self.pushButtonClose)
        self.pushButtonNewUser = QtWidgets.QPushButton(FormList)
        self.pushButtonNewUser.setObjectName("pushButtonNewUser")
        self.verticalLayout.addWidget(self.pushButtonNewUser)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(FormList)
        QtCore.QMetaObject.connectSlotsByName(FormList)
        self.pushButtonClose.clicked.connect(self.closeWindow)
        self.pushButtonNewUser.clicked.connect(self.OpenWindow)

        query = """
            SELECT imie, email, pass FROM users; 
            """
        db = dbConnection()
        db.connect()
        rows = db.fetchall(query)
        db.close()
        
        self.tableWidget.setRowCount(len(rows))
        self.tableWidget.setColumnCount(len(rows[0]))

        for i, row in enumerate(rows):
            for j, val in enumerate(row):
                self.tableWidget.setItem(i, j, QTableWidgetItem(str(val)))

    

    def closeWindow(self):
        FormList.close()

    def OpenWindow(self):
        self.window = QtWidgets.QTabWidget()
        self.ui = Ui_FormMainWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        self.repaint()
    
    def repaint(self):
        self.tableWidget.repaint()

    def retranslateUi(self, FormList):
        _translate = QtCore.QCoreApplication.translate
        FormList.setWindowTitle(_translate("FormList", "Form"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FormList", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FormList", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FormList", "Password"))
        self.pushButtonClose.setText(_translate("FormList", "Close"))
        self.pushButtonNewUser.setText(_translate("FormList", "New User"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormList = QtWidgets.QWidget()
    ui = Ui_FormList()
    ui.setupUi(FormList)
    FormList.show()
    sys.exit(app.exec_())
